import type { Metadata } from "next";
import { Audiowide, Bai_Jamjuree } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import ContactPage from "./contact/page";

const audiowide = Audiowide({
  variable: "--font-audiowide",
  subsets: ["latin"],
  weight: ['400'],
  display: 'swap'
});

const baiJamjuree = Bai_Jamjuree({
  variable: "--font-bai-jamjuree",
  subsets: ["latin"],
  weight:['200' , '300' , '400' , '500' ,'600' ,'700'],
  display: 'swap'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${audiowide.variable} ${baiJamjuree.variable} antialiased`}
      >
        {children}
        <ContactPage/>
        <Footer/>
      </body>
    </html>
  );
}
